#!/usr/bin/env node
/**
 * robot-create.js — Robot template generator (BOT-7, closes #344)
 * Usage: node scripts/robot-create.js <robot-name> [template]
 * Templates: basic, api, scraper, assistant
 */
const fs = require('fs');
const path = require('path');

const ROBOTS_DIR = path.join(__dirname, '..', 'robots');
const toPascalCase = (s) => s.replace(/(^\w|-\w)/g, (m) => m.replace('-', '').toUpperCase());
const toKebab = (s) => s.toLowerCase().replace(/\s+/g, '-');

const TEMPLATES = {
  basic: (name) => `// ${name} — Basic Robot
// Robot ID: ${toKebab(name)}-${Date.now().toString(36)}
class ${toPascalCase(name)}Robot {
  constructor(config = {}) {
    this.name = '${name}';
    this.status = 'idle';
    this.config = config;
  }

  async init() {
    console.log(\`[\${this.name}] Initializing...\`);
    this.status = 'idle';
    return true;
  }

  async execute(job) {
    console.log(\`[\${this.name}] Executing job \${job.jobId}...\`);
    this.status = 'working';
    // TODO: implement job logic
    const result = { success: true, output: 'Job completed' };
    this.status = 'idle';
    return result;
  }

  getStatus() {
    return { name: this.name, status: this.status };
  }
}

module.exports = ${toPascalCase(name)}Robot;
`,

  api: (name) => `// ${name} — API Robot
const axios = require('axios');
class ${toPascalCase(name)}Robot {
  constructor(config = {}) {
    this.name = '${name}';
    this.status = 'idle';
    this.apiKey = config.apiKey || process.env.ROBOT_API_KEY;
    this.baseUrl = config.baseUrl || 'https://api.example.com';
  }

  async init() {
    if (!this.apiKey) throw new Error('API key required for ${name} robot');
    this.status = 'idle';
    return true;
  }

  async execute(job) {
    this.status = 'working';
    try {
      const response = await axios({
        method: job.method || 'GET',
        url: \`\${this.baseUrl}\${job.endpoint}\`,
        headers: { Authorization: \`Bearer \${this.apiKey}\` },
        data: job.payload
      });
      this.status = 'idle';
      return { success: true, data: response.data };
    } catch (err) {
      this.status = 'idle';
      return { success: false, error: err.message };
    }
  }

  getStatus() {
    return { name: this.name, status: this.status };
  }
}
module.exports = ${toPascalCase(name)}Robot;
`,

  scraper: (name) => `// ${name} — Scraper Robot
const axios = require('axios');
class ${toPascalCase(name)}Robot {
  constructor(config = {}) {
    this.name = '${name}';
    this.status = 'idle';
    this.userAgent = config.userAgent || 'MyZubster-Robot/1.0';
  }

  async init() { this.status = 'idle'; return true; }

  async execute(job) {
    this.status = 'working';
    try {
      const response = await axios.get(job.url, {
        headers: { 'User-Agent': this.userAgent }
      });
      this.status = 'idle';
      return { success: true, statusCode: response.status, dataLength: response.data.length };
    } catch (err) {
      this.status = 'idle';
      return { success: false, error: err.message };
    }
  }

  getStatus() {
    return { name: this.name, status: this.status };
  }
}
module.exports = ${toPascalCase(name)}Robot;
`,

  assistant: (name) => `// ${name} — Assistant Robot (uses robot_brain)
const robotBrain = require('../robot_brain');
class ${toPascalCase(name)}Robot {
  constructor(config = {}) {
    this.name = '${name}';
    this.status = 'idle';
    this.personality = config.personality || 'helpful';
  }

  async init() {
    console.log(\`[\${this.name}] Assistant ready (personality: \${this.personality})\`);
    this.status = 'idle';
    return true;
  }

  async execute(job) {
    this.status = 'working';
    const prompt = job.prompt || job.description || 'Help me with this task.';
    try {
      const result = await robotBrain.process({ prompt, robot: this.name });
      this.status = 'idle';
      return { success: true, answer: result };
    } catch (err) {
      this.status = 'idle';
      return { success: false, error: err.message };
    }
  }

  getStatus() {
    return { name: this.name, status: this.status };
  }
}
module.exports = ${toPascalCase(name)}Robot;
`
};

// --- Tests ---
const testsDir = path.join(__dirname, '..', 'tests');
const TEST_TEMPLATE = (name, pascalName) => `// tests/${toKebab(name)}.test.js — Generated by robot-create.js
const ${pascalName}Robot = require('../robots/${toKebab(name)}');

const test = require('node:test');
const assert = require('node:assert');

test('${pascalName}Robot: init returns true', async () => {
  const robot = new ${pascalName}Robot({});
  const result = await robot.init();
  assert.strictEqual(result, true);
});

test('${pascalName}Robot: getStatus returns name and status', () => {
  const robot = new ${pascalName}Robot({});
  const status = robot.getStatus();
  assert.strictEqual(status.name, '${name}');
  assert.strictEqual(status.status, 'idle');
});

test('${pascalName}Robot: execute returns success', async () => {
  const robot = new ${pascalName}Robot({});
  await robot.init();
  const result = await robot.execute({ jobId: 'test-1', description: 'test job' });
  assert.strictEqual(result.success, true);
});
`;

// --- Main ---
const args = process.argv.slice(2);
if (args.length < 1) {
  console.log('Usage: node scripts/robot-create.js <robot-name> [template]');
  console.log('Templates: ' + Object.keys(TEMPLATES).join(', '));
  process.exit(1);
}

const robotName = args[0];
const template = args[1] || 'basic';
const pascalName = toPascalCase(robotName);

if (!TEMPLATES[template]) {
  console.error(`Unknown template: ${template}. Available: ${Object.keys(TEMPLATES).join(', ')}`);
  process.exit(1);
}

// Create robots directory
if (!fs.existsSync(ROBOTS_DIR)) {
  fs.mkdirSync(ROBOTS_DIR, { recursive: true });
}

// Write robot file
const robotFile = path.join(ROBOTS_DIR, `${toKebab(robotName)}.js`);
fs.writeFileSync(robotFile, TEMPLATES[template](robotName));
console.log(`✅ Robot created: ${robotFile} (template: ${template})`);

// Write test file
if (!fs.existsSync(testsDir)) {
  fs.mkdirSync(testsDir, { recursive: true });
}
const testFile = path.join(testsDir, `${toKebab(robotName)}.test.js`);
fs.writeFileSync(testFile, TEST_TEMPLATE(robotName, pascalName));
console.log(`✅ Test created: ${testFile}`);

// Update package.json with robot:create script
const pkgPath = path.join(__dirname, '..', 'package.json');
if (fs.existsSync(pkgPath)) {
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  if (!pkg.scripts) pkg.scripts = {};
  pkg.scripts['robot:create'] = 'node scripts/robot-create.js';
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
  console.log('✅ package.json updated with robot:create script');
}

console.log(`\n🚀 Next: npm run robot:create ${robotName} ${template}`);
