apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - gateway.yaml
  - monero-rpc.yaml
  - explorer.yaml
  - autoscaling.yaml
  - ingress.yaml
